### ISSUE TITLE
[Tracker] Profile Redesign

### ISSUE THREAD

**Issue by HarryKing87** [HarryKing87/pantry-app#122]
In this story I am keeping track of all the sub issues for the Profile Redesign on Pantry Beta. I will be updating this description, until I close all the subtasks.

- [x] Profile Redesign: Implement Location asset #123
- [x] Profile Redesign: Implement Joined asset #124
- [x] Profile Redesign: Implement Food stored info box #125
- [x] Profile Redesign: Implement Food Consumed info box #126
- [x] Profile Redesign: Implement Food Wasted info box #127
- [x] Profile Redesign: Implement profile settings section #128
- [x] Profile Redesign: Pantry Premium banners redesign #129
- [x] Profile Redesign: Implement background photo #131

**Comment by HarryKing87** [comment]
The whole thought of a final result will be similar to the image shown in this subthread
<img width="782" alt="Pantry_Profile_Redesign_Concept" src="https://github.com/HarryKing87/pantry-app/assets/46583043/57d73b9f-c939-407a-acc4-d258bac336ae">

**Comment by HarryKing87** [comment]
Main branch: feature/Profile_Redesign
